// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: leaf-grpc/v1/segment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LeafSegmentServiceClient is the client API for LeafSegmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeafSegmentServiceClient interface {
	// 号段模式
	GenSegmentId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error)
	CreateSegmentId(ctx context.Context, in *LeafAllocDb, opts ...grpc.CallOption) (*CreateSegmentIdResp, error)
	// monitor
	GenSegmentCache(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SegmentBufferCacheViews, error)
	GenSegmentDb(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LeafAllocDbs, error)
}

type leafSegmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafSegmentServiceClient(cc grpc.ClientConnInterface) LeafSegmentServiceClient {
	return &leafSegmentServiceClient{cc}
}

func (c *leafSegmentServiceClient) GenSegmentId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error) {
	out := new(IdReply)
	err := c.cc.Invoke(ctx, "/leafgrpc.v1.LeafSegmentService/GenSegmentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafSegmentServiceClient) CreateSegmentId(ctx context.Context, in *LeafAllocDb, opts ...grpc.CallOption) (*CreateSegmentIdResp, error) {
	out := new(CreateSegmentIdResp)
	err := c.cc.Invoke(ctx, "/leafgrpc.v1.LeafSegmentService/CreateSegmentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafSegmentServiceClient) GenSegmentCache(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SegmentBufferCacheViews, error) {
	out := new(SegmentBufferCacheViews)
	err := c.cc.Invoke(ctx, "/leafgrpc.v1.LeafSegmentService/GenSegmentCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafSegmentServiceClient) GenSegmentDb(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LeafAllocDbs, error) {
	out := new(LeafAllocDbs)
	err := c.cc.Invoke(ctx, "/leafgrpc.v1.LeafSegmentService/GenSegmentDb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeafSegmentServiceServer is the server API for LeafSegmentService service.
// All implementations must embed UnimplementedLeafSegmentServiceServer
// for forward compatibility
type LeafSegmentServiceServer interface {
	// 号段模式
	GenSegmentId(context.Context, *IdRequest) (*IdReply, error)
	CreateSegmentId(context.Context, *LeafAllocDb) (*CreateSegmentIdResp, error)
	// monitor
	GenSegmentCache(context.Context, *IdRequest) (*SegmentBufferCacheViews, error)
	GenSegmentDb(context.Context, *IdRequest) (*LeafAllocDbs, error)
	mustEmbedUnimplementedLeafSegmentServiceServer()
}

// UnimplementedLeafSegmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeafSegmentServiceServer struct {
}

func (UnimplementedLeafSegmentServiceServer) GenSegmentId(context.Context, *IdRequest) (*IdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenSegmentId not implemented")
}
func (UnimplementedLeafSegmentServiceServer) CreateSegmentId(context.Context, *LeafAllocDb) (*CreateSegmentIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSegmentId not implemented")
}
func (UnimplementedLeafSegmentServiceServer) GenSegmentCache(context.Context, *IdRequest) (*SegmentBufferCacheViews, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenSegmentCache not implemented")
}
func (UnimplementedLeafSegmentServiceServer) GenSegmentDb(context.Context, *IdRequest) (*LeafAllocDbs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenSegmentDb not implemented")
}
func (UnimplementedLeafSegmentServiceServer) mustEmbedUnimplementedLeafSegmentServiceServer() {}

// UnsafeLeafSegmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeafSegmentServiceServer will
// result in compilation errors.
type UnsafeLeafSegmentServiceServer interface {
	mustEmbedUnimplementedLeafSegmentServiceServer()
}

func RegisterLeafSegmentServiceServer(s grpc.ServiceRegistrar, srv LeafSegmentServiceServer) {
	s.RegisterService(&LeafSegmentService_ServiceDesc, srv)
}

func _LeafSegmentService_GenSegmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafSegmentServiceServer).GenSegmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leafgrpc.v1.LeafSegmentService/GenSegmentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafSegmentServiceServer).GenSegmentId(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafSegmentService_CreateSegmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeafAllocDb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafSegmentServiceServer).CreateSegmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leafgrpc.v1.LeafSegmentService/CreateSegmentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafSegmentServiceServer).CreateSegmentId(ctx, req.(*LeafAllocDb))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafSegmentService_GenSegmentCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafSegmentServiceServer).GenSegmentCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leafgrpc.v1.LeafSegmentService/GenSegmentCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafSegmentServiceServer).GenSegmentCache(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafSegmentService_GenSegmentDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafSegmentServiceServer).GenSegmentDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leafgrpc.v1.LeafSegmentService/GenSegmentDb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafSegmentServiceServer).GenSegmentDb(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeafSegmentService_ServiceDesc is the grpc.ServiceDesc for LeafSegmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeafSegmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leafgrpc.v1.LeafSegmentService",
	HandlerType: (*LeafSegmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenSegmentId",
			Handler:    _LeafSegmentService_GenSegmentId_Handler,
		},
		{
			MethodName: "CreateSegmentId",
			Handler:    _LeafSegmentService_CreateSegmentId_Handler,
		},
		{
			MethodName: "GenSegmentCache",
			Handler:    _LeafSegmentService_GenSegmentCache_Handler,
		},
		{
			MethodName: "GenSegmentDb",
			Handler:    _LeafSegmentService_GenSegmentDb_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaf-grpc/v1/segment.proto",
}
